### ISSUE TITLE
ability to add a preprompt

### ISSUE THREAD

**Issue by mattwyd** [aandrew-me/tgpt#151]

**Comment by aandrew-me** [comment]
Elaborate

**Comment by kenny-kvibe** [comment]
I think they meant by adding a "system prompt" before the "user prompt",
so that the LLM knows how to behave etc.
but this is not possbile in this case... they just need to be more specific
with their prompts and it will kinda work out.

I wanted to share one interesting thing I just found recently, gonna leave it here:
https://catalog.ngc.nvidia.com/orgs/nvidia/teams/ai-foundation/models/llama2-70b

**Comment by xplshn** [comment]
Yes, he meant that. Which is something I've wanted too, the ability to pass preprompts, for "jailbreaks" or to conditionate the response of the LLM

**Comment by kenny-kvibe** [comment]
https://huggingface.co/spaces

**Comment by mattwyd** [comment]
all it is just appending a predtermined string to all of your prompts so the ai has additional context and you dont have to tell it each time, for example i have chatgpt.com only respond following best practices for code snippets etc

**Comment by EndersNoon** [comment]
You can also create custom bash script function in you .bashrc file.
