### ISSUE TITLE
Error: Vaue is not a valid sequence

### ISSUE THREAD

**Issue by guhitb** [aandrew-me/tgpt#203]
I see the following error any time I try to send a message.
```
Some error has occurred, try again
{"detail":[{"loc":["body","input"],"msg":"value is not a valid sequence","type":"type_error.sequence"}]}
```
Does this effect anyone else? It was working for me yesterday.

**Comment by 0axmx-cx** [comment]
This is the exact same issue I'm having at the moment. I tried uninstalling and reinstalling, and neither of those have helped fix the situation.

**Comment by dannielXdx** [comment]
same issue....__

**Comment by 0axmx-cx** [comment]
If it helps, my output also says:
```Some error has occurred. Statuscode: 422
{"detail":[{"loc":["body","input"],"msg":"value is not a valid sequence","type":"type_error.sequence"}]}
```

I don't know if status code 422 is relevant or not, but I thought I'd mention the full output. It prints this when using it directly:
```
tgpt [prompt]
```

but it prints this when in interactive mode or multiline:
```
Some error has occurred, try again
{"detail":[{"loc":["body","input"],"msg":"value is not a valid sequence","type":"type_error.sequence"}]}
```

**Comment by privet2pizza** [comment]
same issue....

**Comment by aandrew-me** [comment]
Well looks like something is wrong with the default provider. Don't forget guys, there isn't just one provider, phind is working

**Comment by aandrew-me** [comment]
They changed the response structure, update is coming

**Comment by aandrew-me** [comment]
Update is available

**Comment by 0axmx-cx** [comment]
Thank you for the note about switching providers.

I updated and tried switching providers, but I think out of the ones I tried (fakeopen opengpts, koboldai, phind), only koboldai and phind works. I uninstalled, reinstalled, and ran the following commands:

> tgpt --version
```
tgpt 2.5.1
```
> tgpt -u
```
You are already using the latest version. v2.5.1
```
> tgpt --provider fakeopen "What is 1+1"
```
Some error has occurred. Statuscode: 522
error code: 522
```
> tgpt --provider opengpts "What is 1+1"
```
What is 1+1



```
> tgpt --provider koboldai "What is 1+1"
```
What is 1+1

?
The answer is 2.

```
> tgpt --provider phind "What is 1+1"
```
What is 1+1

The sum of 1+1 is 2.

```

**Comment by 0axmx-cx** [comment]
Looked into it, 

[tl;dr: fakeopen is not able to be a provider anymore](https://linux.do/t/topic/1051)

<blockquote>
One year ago, OpenAI released their epoch-making product: ChatGPT, and the whole world went crazy for it.

But in their eyes, China (and of course some countries) seems to be outside the scope of this "world". They block Chinese IP access, block Chinese mobile phone number registration, block Chinese bank card payments, and even block countless computer room IP and VPN manufacturers, and the number is increasing every day.

Maybe they have a reason why they have to do it, but I don't think it should be like this.

About a year ago (2023/02/17 21:58), I made the first commit to the Pandora project, and since then I have started to bypass various blocks of OpenAI. In April 2023, I built a ChatGPT sharing site for netizens who were unable to register an account. It serves netizens who want to experience the charm of ChatGPT for free, without advertising and without diverting traffic. Perhaps because of this, it has received the attention and support of many enthusiastic netizens, quickly expanded thousands of accounts, and the number of daily visits has reached one million or even tens of millions.

In this year, I have competed with OpenAI countless times: passing CF, passing 5-second shield, passing arkose, logging in, registering, etc. I wrote various sub-services and even trained dozens of CAPTCHA recognition models. In the constant struggle, the time, software and hardware costs I need to invest are constantly increasing (over 100 dollars/month). I am used to watching the service monitoring before going to bed every day. When I wake up, I still watch the service monitoring and report problems through private messages in group chats.

I have been well aware of this kind of reverse service since the beginning. If OpenAI changes a parameter, I will lose my leg, but I still enjoy it. Because with a little investment from me, thousands of Chinese people (and of course Russian brothers) can experience the convenience and efficiency improvements brought by advanced technology. I began to slowly understand Mr. Lu Xun’s words: “Infinite distances and countless people are all related to me.”

Of course this won't last. Recently, I realized that OpenAI has been targeting me and started to adjust and target frequently. Their adjustment frequency has begun to be measured in "days" or even "hours". The time and money I need to maintain this service have also increased dramatically, which makes me feel insignificant and powerless, and I can no longer afford it. So I understand that I have already reached the end of this matter.

Some friends said that I should charge an appropriate fee to maintain this project. Yes, this project has no charges, no commercial cooperation, and no advertising from the beginning to the present. This doesn’t mean that I can’t charge, it doesn’t mean that no one wants me for business cooperation, and it doesn’t mean that there are no advertisements to hang on. As for charging, I said in the group that the majority of netizens are caught between GFW and OpenAI, and the cost is already high. I don’t want to take the opportunity to make another cut; for business cooperation, my personal capabilities and resources are limited, and it will be difficult for me to make money after serving the business. I devote my energy to serving netizens; as for advertising, I personally don’t like it.

I am a technical person with no realm and sourness. The above points are my original intentions. If I have to violate them, then I would rather not do them. So let the farewell come! OpenAI, you won, but I leveraged you at a cost far lower than yours. At least so far, you haven’t killed Pandora, and I haven’t lost either.

The server bill will be due on January 30, 2024, and the server will be shut down at that time. Affected services include:

     chat*.zhile.io
     chat-shared*.zhile.io
     chat*.geekgpt.org
     chat.oaifree.com 10.4k
     *.pandoranext.com
     ai*.fakeopen.com

I can only express my sincere apologies for the inconvenience caused to everyone (including ecological partners) by the shutdown of services and servers! Thank you all for your continued support. I hope that the pleasant moments in the process will become good memories, and I hope that you will not take the unpleasant ones to heart. All netizens who have donated free ChatGPT accounts, please also take back your accounts when the time comes. Thank you for your sharing spirit! Please bear with me if there is anything left unfinished.

Finally, I would like to remind you: Although Pandora makes you trust it, it does not mean that products with similar interfaces are worthy of trust. Please pay attention to screening in the future.

As for the future, I should do less continuous reverse engineering projects (which are really very time-consuming). From now on, I will spend more time with my family, chat and joke with netizens here (this thing is very good, you can post articles, comments, private messages, and real-time chat). Yes, he is such an ordinary person.

This moment has finally come
</blockquote>

Creator/Maintainer is most likely changing the default provider to opengpts and is making the appropriate changes to the code to ensure functionality (I also made a pull request to try to help out).

Hope this helps.

**Comment by aandrew-me** [comment]
I fixed the error but looks like this time the server is facing problems

**Comment by aandrew-me** [comment]
Looks like its working fine now
