### ISSUE TITLE
Tgpt for termux 

### ISSUE THREAD

**Issue by Draiga** [aandrew-me/tgpt#53]
Can you make tgpt to be used in Android with the help of tgpt

**Comment by aandrew-me** [comment]
I had tried building for termux but I couldn't succeed. To build for android you need to use an android device. So if you want to use, you need to install `go` on your termux and do `go install github.com/aandrew-me/tgpt@latest`

Otherwise you can instead use this app - https://lesscro.com/rb-chatai-chatgpt-by-bai-v1-0-official/
